package consts

type CURRENCY string

const (
	ETH  CURRENCY = "ETH"
	BTC  CURRENCY = "BTC"
	USDT CURRENCY = "USDT"
	BUSD CURRENCY = "BUSD"
	ADA  CURRENCY = "ADA"
	DOGE CURRENCY = "DOGE"
	DOT  CURRENCY = "DOT"
	LTC  CURRENCY = "LTC"
	BCH  CURRENCY = "BCH"
	XRP  CURRENCY = "XRP"
	SOL  CURRENCY = "SOL"
	LINK CURRENCY = "LINK"
)

type EXCHANGE string

const (
	BINANCE  EXCHANGE = "BINANCE"
	GATEIO   EXCHANGE = "GATE.IO"
	KRAKEN   EXCHANGE = "KRAKEN"
	COINBASE EXCHANGE = "COINBASE"
	BITPAY   EXCHANGE = "BITPAY"
	BITFINEX EXCHANGE = "BITFINEX"
	HUOBI    EXCHANGE = "HUOBI"
	BITSTAMP EXCHANGE = "BITSTAMP"
	KUCOIN   EXCHANGE = "KUCOIN"
	OKX      EXCHANGE = "OKX"
)
